export default {
        title:"animation",
        id:"1",
        route:"animation",
        children:[
            {
                title:"vue-transition",
                id:"1-1",
                route:"vue-transition",
            },{
                title:"anime",
                id:"1-2",
                route:"anime",
                children:[
                    {
                        title:"start",
                        id:"1-2-1",
                        route:"start",
                    },
                ],
            },
        ],
    }