
export default {
    title:"threejs",
    id:"2",
    route:"threejs",
    children:[
        {
            title:"demo",
            id:"2-1",
            route:"demo",
            children:[
                {
                    title:"cuble",
                    id:"2-1-1",
                    route:"cuble",
                },{
                    title:"grid",
                    id:"2-1-2",
                    route:"grid",
                },
            ],
        },{
            title:"1. three.js快速入门",
            id:"2-2",
            route:"start",
            children:[
                {
                    title:"1.第一个3D场景",
                    id:"2-2-1",
                    route:"scene",
                },
                {
                    title:"3.鼠标操作三维场景旋转缩放",
                    id:"2-2-2",
                    route:"control",
                },
                {
                    title:"4.几何体",
                    id:"2-2-3",
                    route:"geometry",
                },
                {
                    title:"5.材质",
                    id:"2-2-3",
                    route:"material",
                },
            ],
        },{
            title:"2、顶点概念、几何体结构",
            id:"2-3",
            route:"vertices-geometry",
            children:[
                {
                    title:"1.2.3.顶点位置 颜色 法向量光照",
                    id:"2-3-1",
                    route:"vertices",
                },
                {
                    title:"4.顶点索引复用顶点数据",
                    id:"2-3-4",
                    route:"vertices-index",
                },
                {
                    title:"5.设置Geometry",
                    id:"2-3-5",
                    route:"objgeometry",
                },
                {
                    title:"6.设置Geometry三角面",
                    id:"2-3-6",
                    route:"objgeometry-face",
                },
                {
                    title:"7.访问几何体对象的数据",
                    id:"2-3-7",
                    route:"objgeometry-data",
                },
                {
                    title:"8.旋转平移缩放变换、复制、克隆",
                    id:"2-3-8",
                    route:"objgeometry-operation",
                },
            ]
        },
    ],
}
