
export default {
    title:"threejs",
    id:"2",
    route:"threejs",
    children:[
        {
            title:"demo",
            id:"2-1",
            route:"demo",
            children:[
                {
                    title:"cuble",
                    id:"2-1-1",
                    route:"cuble",
                },{
                    title:"grid",
                    id:"2-1-2",
                    route:"grid",
                },
            ],
        },{
            title:"1. three.js快速入门",
            id:"2-2",
            route:"start",
            children:[
                {
                    title:"1.第一个3D场景",
                    id:"2-2-1",
                    route:"scene",
                },
                {
                    title:"3.鼠标操作三维场景旋转缩放",
                    id:"2-2-2",
                    route:"control",
                },
                {
                    title:"4.几何体",
                    id:"2-2-3",
                    route:"geometry",
                },
            ],
        },
    ],
}
