export default {
    title:"web",
    id:"web",
    route:"web",
    children:[
        {
            title:"index",
            id:"web-index",
            route:"index",
        },
        {
            title:"shadow-dom",
            id:"shadow-dom",
            route:"shadow-dom",
        },
        {
            title:"custom-elements",
            id:"custom-elements",
            route:"custom-elements",
        },
    ],
}